version: "3.1"

services:
  oracledb:
    build:
      context: ./oracledb
    expose:
      - "1521"
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - "oradata:/opt/oracle/oradata"

  wildfly-oracle:
    image: caspard/wildfly-oracle
    depends_on:
      - oracledb
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
    environment:
      - WILDFLY_ADMIN_PASSWORD=changeit
      - WILDFLY_DATASOURCE_URL=jdbc:oracle:thin:@//oracledb:1521/ORCLPDB1
      - WILDFLY_DATASOURCE_USERNAME=myschema
      - WILDFLY_DATASOURCE_PASSWORD=myschema

volumes:
  oradata:
